main:
  output: ~/performance_info/
  performance_results: /tmp/w3af-*
  ec2_instance_size: m1.small
  security_group: collector
  keypair: collector
  ami: ami-0b9c9f62
  user: ubuntu

setup:
  - setup_apt.sh
  - setup_psutil.sh
  - install_w3af.sh

run:
  - run_w3af.sh:
    - timeout: 10

before_collect:
  - pkill_w3af.sh
  - get_sys_perf_data.py
  - get_http_perf_data.sh