main:
  output: ~/performance_info/
  performance_results: /tmp/*w3af*
  ec2_instance_size: m1.small
  security_group: collector
  keypair: collector
  ami: ami-0b9c9f62
  user: ubuntu

setup:
  - install_w3af.sh

run:
  - run_w3af.sh:
    - timeout: 1h

before_collect:
  - get_perf_data.sh