main:
  output: ~/performance-info/
  performance_results: /tmp/collector/w3af-*
  ec2_instance_size: m3.medium
  security_group: collector
  keypair: collector2
  ami: ami-feade294
  user: ubuntu
  S3: w3af-performance-data

setup:
  # We want to run w3af inside docker
  - install_dependencies.sh

  # Contains the w3af scan configuration
  - setup.sh

run:
  # Runs w3af
  - run_docker.sh:
    - timeout: 25
    - warn_only: true

before_collect:
  - pkill_w3af.sh
  - get_sys_perf_data.py
  - get_http_perf_data.sh