main:
  output: ~/performance_info/
  performance_results: /tmp/collector/w3af-*
  ec2_instance_size: m1.small
  security_group: collector
  keypair: collector2
  ami: ami-38c3cb50
  user: ubuntu
  S3: w3af-performance-data

setup:
  # We want to run w3af inside docker
  - install_dependencies.sh

  # Contains the w3af scan configuration
  - setup.sh

run:
  # Runs w3af
  - run_docker.sh:
    - timeout: 240
    - warn_only: true

before_collect:
  - pkill_w3af.sh
  - get_sys_perf_data.py
  - get_http_perf_data.sh